---
# 🔵 PROJECT 1 — NumPy Data Explorer
**Topics:** Array creation, indexing, slicing, math/statistical ops, reshaping, broadcasting, save/load, performance comparison

---

In [1]:
import numpy as np
import time
print(f"NumPy version: {np.__version__}")

NumPy version: 2.0.2


## 1.1 — Array Creation

In [2]:
# --- 1D Array ---
arr1d = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1d)

# --- 2D Array ---
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print("\n2D Array:\n", arr2d)

# --- 3D Array ---
arr3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("\n3D Array:\n", arr3d)

# --- Special Arrays ---
zeros  = np.zeros((3, 4))
ones   = np.ones((2, 3))
eye    = np.eye(3)
rng    = np.arange(0, 20, 2)
lin    = np.linspace(0, 1, 6)
rand   = np.random.rand(3, 3)
randn  = np.random.randn(3, 3)
randint= np.random.randint(1, 100, (3, 3))

print("\nZeros:\n",  zeros)
print("\nOnes:\n",   ones)
print("\nIdentity:\n", eye)
print("\nArange:",   rng)
print("Linspace:",   lin)
print("\nRandom (uniform):\n",  rand)
print("Random (normal):\n",    randn)
print("Random integers:\n",    randint)

print("\n--- Array Properties ---")
print("Shape:",   arr2d.shape)
print("Size:",    arr2d.size)
print("Ndim:",    arr2d.ndim)
print("Dtype:",   arr2d.dtype)
print("Itemsize:",arr2d.itemsize, "bytes")

1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Arange: [ 0  2  4  6  8 10 12 14 16 18]
Linspace: [0.  0.2 0.4 0.6 0.8 1. ]

Random (uniform):
 [[0.07086847 0.92714475 0.24181135]
 [0.5582767  0.60726494 0.74385511]
 [0.86281692 0.90883772 0.74400888]]
Random (normal):
 [[-1.52593661  0.56666597  1.68823837]
 [-0.87212418 -0.50632567 -1.32654876]
 [-0.1594179   0.68443153 -0.07743166]]
Random integers:
 [[53 96 36]
 [87 14 64]
 [10 46 28]]

--- Array Properties ---
Shape: (3, 3)
Size: 9
Ndim: 2
Dtype: int64
Itemsize: 8 bytes


## 1.2 — Indexing & Slicing

In [3]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90,100,110,120]])

print("Full Array:\n", arr)

# Indexing
print("\nElement [0,0]:",  arr[0, 0])
print("Element [1,2]:",    arr[1, 2])
print("Element [-1,-1]:",  arr[-1, -1])

# Slicing rows
print("\nRow 0:",          arr[0])
print("Row 1:",            arr[1])
print("Last row:",         arr[-1])

# Slicing columns
print("\nColumn 0:",       arr[:, 0])
print("Column 2:",         arr[:, 2])

# Sub-arrays
print("\nRows 0-1, Cols 1-2:\n", arr[0:2, 1:3])
print("Every 2nd col:\n",         arr[:, ::2])

# Boolean indexing
print("\nElements > 60:",  arr[arr > 60])

# Fancy indexing
print("Rows [0, 2]:\n",    arr[[0, 2]])
print("Cols [1, 3]:\n",    arr[:, [1, 3]])

Full Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element [0,0]: 10
Element [1,2]: 70
Element [-1,-1]: 120

Row 0: [10 20 30 40]
Row 1: [50 60 70 80]
Last row: [ 90 100 110 120]

Column 0: [10 50 90]
Column 2: [ 30  70 110]

Rows 0-1, Cols 1-2:
 [[20 30]
 [60 70]]
Every 2nd col:
 [[ 10  30]
 [ 50  70]
 [ 90 110]]

Elements > 60: [ 70  80  90 100 110 120]
Rows [0, 2]:
 [[ 10  20  30  40]
 [ 90 100 110 120]]
Cols [1, 3]:
 [[ 20  40]
 [ 60  80]
 [100 120]]


## 1.3 — Mathematical Operations

In [5]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[10, 20, 30],
              [40, 50, 60]])

print("A:\n", a)
print("B:\n", b)

# Element-wise operations
print("\nA + B:\n",   a + b)
print("A - B:\n",     a - b)
print("A * B:\n",     a * b)
print("A / B:\n",     a / b)
print("A ** 2:\n",    a ** 2)
print("A % 2:\n",     a % 2)

# Scalar operations
print("\nA + 100:\n", a + 100)
print("A * 3:\n",     a * 3)

# Math functions
print("\nsqrt(A):\n",     np.sqrt(a))
print("exp(A):\n",        np.exp(a))
print("log(A):\n",        np.log(a))
print("abs(-A):\n",       np.abs(-a))
print("sin(A):\n",        np.sin(a))

# Matrix multiplication
c = np.array([[1, 2], [3, 4], [5, 6]])
print("\nDot product (A @ C):\n", np.dot(a, c))
print("Matrix multiply:\n",          a @ c)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[10 20 30]
 [40 50 60]]

A + B:
 [[11 22 33]
 [44 55 66]]
A - B:
 [[ -9 -18 -27]
 [-36 -45 -54]]
A * B:
 [[ 10  40  90]
 [160 250 360]]
A / B:
 [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
A ** 2:
 [[ 1  4  9]
 [16 25 36]]
A % 2:
 [[1 0 1]
 [0 1 0]]

A + 100:
 [[101 102 103]
 [104 105 106]]
A * 3:
 [[ 3  6  9]
 [12 15 18]]

sqrt(A):
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
exp(A):
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
log(A):
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]
abs(-A):
 [[1 2 3]
 [4 5 6]]
sin(A):
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

Dot product (A @ C):
 [[22 28]
 [49 64]]
Matrix multiply:
 [[22 28]
 [49 64]]


## 1.4 — Axis-wise & Statistical Operations

In [6]:
data = np.array([[4, 7, 2, 9],
                 [1, 8, 5, 3],
                 [6, 0, 11, 4]])
print("Data:\n", data)

# Global stats
print("\n--- Global ---")
print("Sum:",    data.sum())
print("Mean:",   data.mean())
print("Std:",    data.std())
print("Var:",    data.var())
print("Min:",    data.min())
print("Max:",    data.max())
print("Median:", np.median(data))

# Axis 0 = column-wise (down rows)
print("\n--- Axis 0 (column-wise) ---")
print("Sum:",    data.sum(axis=0))
print("Mean:",   data.mean(axis=0))
print("Min:",    data.min(axis=0))
print("Max:",    data.max(axis=0))

# Axis 1 = row-wise (across columns)
print("\n--- Axis 1 (row-wise) ---")
print("Sum:",    data.sum(axis=1))
print("Mean:",   data.mean(axis=1))
print("Min:",    data.min(axis=1))
print("Max:",    data.max(axis=1))

# Sorting & arg functions
print("\nArgmax (global):",  data.argmax())
print("Argmin (global):",    data.argmin())
print("Argsort (row 0):",    np.argsort(data[0]))
print("Sorted data (axis=1):\n", np.sort(data, axis=1))

# Percentile & quantile
print("\n25th percentile:", np.percentile(data, 25))
print("75th percentile:",   np.percentile(data, 75))
print("Correlation matrix:\n", np.corrcoef(data))

Data:
 [[ 4  7  2  9]
 [ 1  8  5  3]
 [ 6  0 11  4]]

--- Global ---
Sum: 60
Mean: 5.0
Std: 3.1885210782848317
Var: 10.166666666666666
Min: 0
Max: 11
Median: 4.5

--- Axis 0 (column-wise) ---
Sum: [11 15 18 16]
Mean: [3.66666667 5.         6.         5.33333333]
Min: [1 0 2 3]
Max: [ 6  8 11  9]

--- Axis 1 (row-wise) ---
Sum: [22 17 21]
Mean: [5.5  4.25 5.25]
Min: [2 1 0]
Max: [ 9  8 11]

Argmax (global): 10
Argmin (global): 9
Argsort (row 0): [2 0 1 3]
Sorted data (axis=1):
 [[ 2  4  7  9]
 [ 1  3  5  8]
 [ 0  4  6 11]]

25th percentile: 2.75
75th percentile: 7.25
Correlation matrix:
 [[ 1.          0.12566292 -0.78530605]
 [ 0.12566292  1.         -0.39662913]
 [-0.78530605 -0.39662913  1.        ]]


## 1.5 — Reshaping & Broadcasting

In [7]:
arr = np.arange(1, 25)
print("Original (1D, 24 elements):", arr)

# Reshape
r1 = arr.reshape(4, 6)
r2 = arr.reshape(2, 3, 4)
r3 = arr.reshape(6, -1)          # -1 auto-calculates
print("\nReshaped (4x6):\n", r1)
print("Reshaped (2x3x4):\n", r2)
print("Reshaped (6x?):\n", r3)

# Flatten & Ravel
print("\nFlatten:", r1.flatten())
print("Ravel:",    r1.ravel())

# Transpose
print("\nTranspose of (4x6):", r1.T.shape, "\n", r1.T)

# --- Broadcasting ---
print("\n--- Broadcasting ---")
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_vec = np.array([10, 20, 30])
col_vec = np.array([[10], [20], [30]])

print("Matrix:\n", matrix)
print("Row vector:", row_vec)
print("Matrix + Row vector (broadcast):\n", matrix + row_vec)
print("Matrix + Col vector (broadcast):\n", matrix + col_vec)

# Expand dims
v = np.array([1, 2, 3])
print("\nOriginal shape:", v.shape)
print("Expand axis 0:",   np.expand_dims(v, axis=0).shape)
print("Expand axis 1:",   np.expand_dims(v, axis=1).shape)

# Squeeze
s = np.array([[[1, 2, 3]]])  # shape (1,1,3)
print("\nBefore squeeze:", s.shape)
print("After squeeze:",    np.squeeze(s).shape)

# Stack & concatenate
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nvstack:\n",  np.vstack([a, b]))
print("hstack:",      np.hstack([a, b]))
print("stack axis=0:\n", np.stack([a, b], axis=0))
print("concatenate:",    np.concatenate([a, b]))

Original (1D, 24 elements): [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Reshaped (4x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Reshaped (2x3x4):
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Reshaped (6x?):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Flatten: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Ravel: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]

Transpose of (4x6): (6, 4) 
 [[ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]
 [ 6 12 18 24]]

--- Broadcasting ---
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row vector: [10 20 30]
Matrix + Row vector (broadcast):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Matrix + Col vector (broadcast):
 [[11 12 13]
 [24 25 26]
 [37 38 39]]

Original shape: (3,)
Expand axis 0: (1, 3)
Expand axis 1:

## 1.6 — Save & Load NumPy Arrays

In [8]:
original = np.random.randint(1, 100, (4, 5))
print("Original Array:\n", original)

# --- Save / Load single array (.npy) ---
np.save('my_array.npy', original)
loaded = np.load('my_array.npy')
print("\nLoaded from .npy:\n",    loaded)
print("Arrays equal:",             np.array_equal(original, loaded))

# --- Save / Load multiple arrays (.npz) ---
a = np.array([1, 2, 3])
b = np.array([[4, 5], [6, 7]])
np.savez('multi_arrays.npz', array_a=a, array_b=b)

data = np.load('multi_arrays.npz')
print("\nLoaded .npz keys:", list(data.keys()))
print("array_a:",            data['array_a'])
print("array_b:\n",          data['array_b'])

# --- Save / Load as text (.txt / .csv) ---
np.savetxt('array.txt', original, delimiter=',', fmt='%d', header='col1,col2,col3,col4,col5')
txt_loaded = np.loadtxt('array.txt', delimiter=',', skiprows=1)
print("\nLoaded from .txt:\n", txt_loaded)

print("\nSave/Load operations completed successfully!")

Original Array:
 [[67 31 50  3 81]
 [92 16 86  6 78]
 [98  8 60 85 53]
 [54 55 46 37 95]]

Loaded from .npy:
 [[67 31 50  3 81]
 [92 16 86  6 78]
 [98  8 60 85 53]
 [54 55 46 37 95]]
Arrays equal: True

Loaded .npz keys: ['array_a', 'array_b']
array_a: [1 2 3]
array_b:
 [[4 5]
 [6 7]]

Loaded from .txt:
 [[67. 31. 50.  3. 81.]
 [92. 16. 86.  6. 78.]
 [98.  8. 60. 85. 53.]
 [54. 55. 46. 37. 95.]]

Save/Load operations completed successfully!


## 1.7 — NumPy vs Python Lists Performance Comparison

In [9]:
SIZE = 1_000_000
print(f"Comparing NumPy vs Python List on {SIZE:,} elements")
print("=" * 55)

# ---- Creation ----
t0 = time.time()
py_list = list(range(SIZE))
t_list_create = time.time() - t0

t0 = time.time()
np_arr = np.arange(SIZE)
t_np_create = time.time() - t0

print(f"\nCreation:")
print(f"  Python list : {t_list_create:.5f} s")
print(f"  NumPy array : {t_np_create:.5f} s")
print(f"  Speedup     : {t_list_create/t_np_create:.1f}x")

# ---- Sum ----
t0 = time.time()
s1 = sum(py_list)
t_list_sum = time.time() - t0

t0 = time.time()
s2 = np_arr.sum()
t_np_sum = time.time() - t0

print(f"\nSum:")
print(f"  Python list : {t_list_sum:.5f} s")
print(f"  NumPy array : {t_np_sum:.5f} s")
print(f"  Speedup     : {t_list_sum/t_np_sum:.1f}x")

# ---- Element-wise multiply by 2 ----
t0 = time.time()
res1 = [x * 2 for x in py_list]
t_list_mul = time.time() - t0

t0 = time.time()
res2 = np_arr * 2
t_np_mul = time.time() - t0

print(f"\nElement-wise Multiply by 2:")
print(f"  Python list : {t_list_mul:.5f} s")
print(f"  NumPy array : {t_np_mul:.5f} s")
print(f"  Speedup     : {t_list_mul/t_np_mul:.1f}x")

# ---- Memory usage ----
import sys
list_mem = sys.getsizeof(py_list) + sum(sys.getsizeof(x) for x in py_list[:100]) * 10000
np_mem   = np_arr.nbytes

print(f"\nMemory Usage (approx):")
print(f"  NumPy array : {np_mem / 1024 / 1024:.2f} MB")
print(f"  (Python list uses significantly more due to object overhead)")

print("\nProject 1 — NumPy Data Explorer Complete!")

Comparing NumPy vs Python List on 1,000,000 elements

Creation:
  Python list : 0.04944 s
  NumPy array : 0.00531 s
  Speedup     : 9.3x

Sum:
  Python list : 0.01578 s
  NumPy array : 0.00114 s
  Speedup     : 13.8x

Element-wise Multiply by 2:
  Python list : 0.08836 s
  NumPy array : 0.00973 s
  Speedup     : 9.1x

Memory Usage (approx):
  NumPy array : 7.63 MB
  (Python list uses significantly more due to object overhead)

Project 1 — NumPy Data Explorer Complete!
